import { NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

const productsFilePath = path.join(process.cwd(), 'lib', 'products.js');

async function readProducts() {
    try {
        const fileContent = await fs.readFile(productsFilePath, 'utf-8');
        const match = fileContent.match(/export const products = (\[[\s\S]*?\]);/);
        if (match) return eval(match[1]);
        return [];
    } catch (error) { return []; }
}

async function writeProducts(products) {
    const fileContent = `// Products data - Auto-generated by Admin Panel
// Last updated: ${new Date().toISOString()}

export const products = ${JSON.stringify(products, null, 2)};

export function getProductById(id) { return products.find(product => product.id === id); }
export function getProductsByCategory(category) { return products.filter(product => product.category === category); }
export function getCategories() { return [...new Set(products.map(product => product.category))]; }
`;
    await fs.writeFile(productsFilePath, fileContent, 'utf-8');
}

export async function GET(request, { params }) {
    try {
        const { id } = params;
        const products = await readProducts();
        const product = products.find(p => p.id === id);
        if (!product) return NextResponse.json({ success: false, error: 'Product not found' }, { status: 404 });
        return NextResponse.json({ success: true, product });
    } catch (error) {
        return NextResponse.json({ success: false, error: 'Failed to fetch product' }, { status: 500 });
    }
}

export async function PUT(request, { params }) {
    try {
        const { id } = params;
        const body = await request.json();
        const { name, productCode, price, category, description, image, images, features, inStock } = body;

        const products = await readProducts();
        const productIndex = products.findIndex(p => p.id === id);
        if (productIndex === -1) return NextResponse.json({ success: false, error: 'Product not found' }, { status: 404 });

        const updatedProduct = {
            ...products[productIndex],
            name: name || products[productIndex].name,
            productCode: productCode || products[productIndex].productCode,
            price: price !== undefined ? parseFloat(price) : products[productIndex].price,
            category: category || products[productIndex].category,
            description: description !== undefined ? description : products[productIndex].description,
            image: image !== undefined ? image : products[productIndex].image,
            images: images !== undefined ? images : products[productIndex].images,
            features: features !== undefined ? features : products[productIndex].features,
            inStock: inStock !== undefined ? inStock : products[productIndex].inStock
        };

        products[productIndex] = updatedProduct;
        await writeProducts(products);

        return NextResponse.json({ success: true, product: updatedProduct });
    } catch (error) {
        return NextResponse.json({ success: false, error: 'Failed to update product' }, { status: 500 });
    }
}

export async function DELETE(request, { params }) {
    try {
        const { id } = params;
        const products = await readProducts();
        const productIndex = products.findIndex(p => p.id === id);
        if (productIndex === -1) return NextResponse.json({ success: false, error: 'Product not found' }, { status: 404 });

        const deletedProduct = products.splice(productIndex, 1)[0];
        await writeProducts(products);

        return NextResponse.json({ success: true, message: 'Product deleted', product: deletedProduct });
    } catch (error) {
        return NextResponse.json({ success: false, error: 'Failed to delete product' }, { status: 500 });
    }
}
