import { Crown, Activity, Sparkles, Heart } from 'lucide-react';

// Single source of truth for the four watch subcategories — consumed by the
// header mega-menu, the /watches landing page, and each category page template.
export const watchCategories = [
  {
    slug: 'premium',
    name: 'Premium',
    emoji: '👑',
    icon: Crown,
    description: 'Luxury timepieces for the distinguished',
    apiCategory: 'premium-watches',
    headingLine2: 'Timepieces',
    heroBadgeLabel: 'Luxury Collection',
    tagline: 'Handpicked luxury watches for those who appreciate precision craftsmanship and timeless elegance.',
    tileColor: 'bg-amber-50 border-amber-200 hover:border-amber-300',
    theme: {
      pillBg: 'bg-amber-50 border-amber-200',
      pillIcon: 'text-amber-500',
      pillText: 'text-amber-700',
      headlineAccent: 'text-amber-500',
      statAccent: 'text-amber-500',
      filledBtn: 'bg-amber-500 border-amber-500',
      hoverBorder: 'hover:border-amber-300',
      focusBorder: 'focus:border-amber-400',
      ribbonBg: 'bg-amber-500',
      nameHover: 'group-hover:text-amber-600',
      featureTag: 'bg-amber-50 text-amber-700',
      glow: 'from-amber-200/40',
      ring: 'border-amber-500/15',
      emptyIconBg: 'bg-amber-50',
      emptyIconText: 'text-amber-400',
      emptyBtn: 'bg-amber-500 hover:bg-amber-600',
    },
    priceBands: [
      { value: 'under-4000', label: 'Under Rs. 4,000', test: (p) => p < 4000 },
      { value: '4000-6000', label: 'Rs. 4,000 – 6,000', test: (p) => p >= 4000 && p <= 6000 },
      { value: 'above-6000', label: 'Above Rs. 6,000', test: (p) => p > 6000 },
    ],
  },
  {
    slug: 'casual',
    name: 'Casual',
    emoji: '⌚',
    icon: Activity,
    description: 'Everyday elegance and comfort',
    apiCategory: 'casual-watches',
    headingLine2: 'Watches',
    heroBadgeLabel: 'Active Lifestyle Collection',
    tagline: 'Built for your active lifestyle — functionality and comfort for the everyday explorer.',
    tileColor: 'bg-stone-50 border-stone-200 hover:border-stone-300',
    theme: {
      pillBg: 'bg-teal-50 border-teal-200',
      pillIcon: 'text-teal-600',
      pillText: 'text-teal-700',
      headlineAccent: 'text-teal-600',
      statAccent: 'text-teal-600',
      filledBtn: 'bg-teal-600 border-teal-600',
      hoverBorder: 'hover:border-teal-300',
      focusBorder: 'focus:border-teal-400',
      ribbonBg: 'bg-teal-600',
      nameHover: 'group-hover:text-teal-600',
      featureTag: 'bg-teal-50 text-teal-700',
      glow: 'from-teal-200/40',
      ring: 'border-teal-500/15',
      emptyIconBg: 'bg-teal-50',
      emptyIconText: 'text-teal-500',
      emptyBtn: 'bg-teal-600 hover:bg-teal-700',
    },
    priceBands: [
      { value: 'under-2000', label: 'Under Rs. 2,000', test: (p) => p < 2000 },
      { value: '2000-3500', label: 'Rs. 2,000 – 3,500', test: (p) => p >= 2000 && p <= 3500 },
      { value: 'above-3500', label: 'Above Rs. 3,500', test: (p) => p > 3500 },
    ],
  },
  {
    slug: 'stylish',
    name: 'Stylish',
    emoji: '✨',
    icon: Sparkles,
    description: 'Fashion-forward statement pieces',
    apiCategory: 'stylish-watches',
    headingLine2: 'Watches',
    heroBadgeLabel: 'Fashion-Forward Collection',
    // Pinned hero pick — falls back to the highest-priced item if this slug isn't found
    featuredSlug: 'denvosi-franck-muller-white-ice',
    tagline: 'Fashion-forward timepieces for those who make a statement in everything they wear.',
    tileColor: 'bg-violet-50 border-violet-200 hover:border-violet-300',
    theme: {
      pillBg: 'bg-violet-50 border-violet-200',
      pillIcon: 'text-violet-600',
      pillText: 'text-violet-700',
      headlineAccent: 'text-violet-600',
      statAccent: 'text-violet-600',
      filledBtn: 'bg-violet-600 border-violet-600',
      hoverBorder: 'hover:border-violet-300',
      focusBorder: 'focus:border-violet-400',
      ribbonBg: 'bg-violet-600',
      nameHover: 'group-hover:text-violet-600',
      featureTag: 'bg-violet-50 text-violet-700',
      glow: 'from-violet-200/40',
      ring: 'border-violet-500/15',
      emptyIconBg: 'bg-violet-50',
      emptyIconText: 'text-violet-500',
      emptyBtn: 'bg-violet-600 hover:bg-violet-700',
    },
    priceBands: [
      { value: 'under-3800', label: 'Under Rs. 3,800', test: (p) => p < 3800 },
      { value: '3800-4400', label: 'Rs. 3,800 – 4,400', test: (p) => p >= 3800 && p <= 4400 },
      { value: 'above-4400', label: 'Above Rs. 4,400', test: (p) => p > 4400 },
    ],
  },
  {
    slug: 'women',
    name: "Women's",
    emoji: '💎',
    icon: Heart,
    description: 'Elegant timepieces for women',
    apiCategory: 'women-watches',
    headingLine2: 'Watches',
    heroBadgeLabel: 'Elegant Collection',
    tagline: 'Refined, elegant timepieces designed for the modern woman.',
    tileColor: 'bg-rose-50 border-rose-200 hover:border-rose-300',
    theme: {
      pillBg: 'bg-rose-50 border-rose-200',
      pillIcon: 'text-rose-500',
      pillText: 'text-rose-700',
      headlineAccent: 'text-rose-500',
      statAccent: 'text-rose-500',
      filledBtn: 'bg-rose-500 border-rose-500',
      hoverBorder: 'hover:border-rose-300',
      focusBorder: 'focus:border-rose-400',
      ribbonBg: 'bg-rose-500',
      nameHover: 'group-hover:text-rose-600',
      featureTag: 'bg-rose-50 text-rose-700',
      glow: 'from-rose-200/40',
      ring: 'border-rose-500/15',
      emptyIconBg: 'bg-rose-50',
      emptyIconText: 'text-rose-400',
      emptyBtn: 'bg-rose-500 hover:bg-rose-600',
    },
    priceBands: [
      { value: 'under-2000', label: 'Under Rs. 2,000', test: (p) => p < 2000 },
      { value: '2000-3500', label: 'Rs. 2,000 – 3,500', test: (p) => p >= 2000 && p <= 3500 },
      { value: 'above-3500', label: 'Above Rs. 3,500', test: (p) => p > 3500 },
    ],
  },
];

export const getWatchCategory = (slug) => watchCategories.find((c) => c.slug === slug);
